jwt:
  config:
    key: secret
    ttl: 600000
    remember: 604800000

custom:
  config:
    ignores:
      get:
        - "/favicon.ico"
        - "/doc.html"
        - "/css/**"
        - "/js/**"
        - "/docs/**"
        - "/webjars/**"
        - "/v2/api-docs"
        - "/v2/api-docs-ext"
        - "/swagger-resources/**"
      # 需要过滤的 post 请求
      post:
        - "/api/auth/login"
        - "/api/auth/logout"
      # 需要过滤的请求，不限方法
      pattern:
        - "/test/*"
